version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volume:
      - ./backend/data:/data
    ports:
      - "27170":"27170"
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000":"5000"
    depends_on:
       - mongodb
  frontend:
    conatiner_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173":"5173"

volumes:
  data:
